### ISSUE TITLE
website hangs along with UI stuttering

### ISSUE THREAD

**Issue by alnmy** [secureblue/hardened-chromium#30] opened 2024-08-02 11:16 UTC
this website hangs after a few seconds https://account.protonvpn.com/downloads when logged in
chromium UI stutters really badly when set to GTK, not so bad but still happens when using "Classic" theme
using secureblue gnome hardened, issue happened even when i had no modifications to the OS 
version of secureblue: https://github.com/secureblue/secureblue/pkgs/container/silverblue-main-hardened/252280346?tag=9f56f2f-40

video of stuttering. it doesn't look that bad on video but having input delayed by ~0.7 seconds consistently is quite an obvious issue.
https://github.com/user-attachments/assets/f0aa9ce2-e6fe-4058-a94d-f028597c76da

**Comment by qoijjj** [comment] 2024-08-02 15:33
@alnmy are you able to reproduce on a userns image?

also, can you provide the output of all of the following:

`cat /etc/chromium/chromium.conf`
`sudo audit2allow -a`
`ujust check-local-overrides`

**Comment by alnmy** [comment] 2024-08-02 15:45
> When did the issue start? Could you also provide the version you are using? Of the browser, that is.

ever since i started using secure blue last night. 127.0.6533.88 (Official Build) hardened-chromium (64-bit) 



> @alnmy are you able to reproduce on a userns image?
> 
> also, can you provide the output of all of the following:
> 
> `cat /etc/chromium/chromium.conf` `sudo audit2allow -a` `ujust check-local-overrides`

stuttering doesn't happen on userns seemingly. protonvpn site crashes though

[chromium.conf](https://pastebin.com/raw/qceP9Yxq)
[audit2allow -a](https://pastebin.com/raw/Yw4SQyzR)
[ujust check-local-overrides](https://pastebin.com/raw/96XQ33XS)

**Comment by qoijjj** [comment] 2024-08-02 16:10
@alnmy does protonvpn still crash if you enable the v8 optimizer for protonvpn in site settings/

**Comment by qoijjj** [comment] 2024-08-02 16:13
also can you screenshot `chrome://gpu`

**Comment by alnmy** [comment] 2024-08-02 16:28
> > protonvpn site crashes though
> 
> On userns images?

yes



> @alnmy does protonvpn still crash if you enable the v8 optimizer for protonvpn in site settings/

yes



> also can you screenshot `chrome://gpu`

![image](https://github.com/user-attachments/assets/0372edee-b025-4518-95b6-9c068fd20913)

**Comment by qoijjj** [comment] 2024-08-02 16:32
@alnmy what are the steps to replicate the crash?
do you just go to protonvpn.com and the page crashes? also, what do you mean by crash?

**Comment by qoijjj** [comment] 2024-08-02 16:41
wait in the original post you said "this website hangs after a few seconds" but then you said it crashes

can you clarify

**Comment by alnmy** [comment] 2024-08-02 16:43
> wait in the original post you said "this website hangs after a few seconds" but then you said it crashes
> 
> can you clarify

It's more so being "unresponsive". The Chromium "Pages unresponsive" prompt appears after about 30 seconds of the page hanging. The page hangs after being on it for a few seconds.

The steps to replicate the crash are to log into ProtonVPN and go to the "Downloads" page.

**Comment by qoijjj** [comment] 2024-08-02 16:49
@alnmy can you start the browser using the terminal by just typing `chromium-browser` and copy the logs?

also can you provide `rpm-ostree status` and cpu/gpu info?

**Comment by alnmy** [comment] 2024-08-02 17:15
For whatever reason, instead of the page going "unresponsive", the page now becomes responsive after about a minute of waiting. 

![image](https://github.com/user-attachments/assets/a008998a-51c5-43df-9f16-108b5ee96a28)

[rpm-ostree](https://pastebin.com/raw/zakm7w4s)
cpu: ryzen 2600
gpu: rx 6700xt

Using a profiler, it can be seen that there was a function which took about 35 seconds.
![image](https://github.com/user-attachments/assets/184f9d83-38ef-4dd4-a8bf-63ad2d1a367c)

**Comment by alnmy** [comment] 2024-08-02 17:16
[logs](https://pastebin.com/raw/KHH6BWCu)

**Comment by qoijjj** [comment] 2024-08-02 17:19
@alnmy and you have the v8 optimizer enabled for account.protonvpn.com?

Also, does that site hang on regular chrome?

I remember seeing slowness on that page before, but I assumed it was just a poorly optimized page :smile:

**Comment by alnmy** [comment] 2024-08-02 17:21
> @alnmy and you have the v8 optimizer enabled for account.protonvpn.com?
> 
> Also, does that site hang on regular chrome?
> 
> I remember seeing slowness on that page before, but I assumed it was just a poorly optimized page 😄

V8 optimiser is enabled and I have never experienced this page hanging before.

**Comment by qoijjj** [comment] 2024-08-02 17:22
@alnmy got it, I can reproduce this.

**Comment by qoijjj** [comment] 2024-08-02 17:23
I've seen it mildly slow before but never like this, yeah

**Comment by qoijjj** [comment] 2024-08-02 17:23
@alnmy are you able to repro on google chrome?

**Comment by qoijjj** [comment] 2024-08-02 17:28
@alnmy I am able to repro but after waiting for about a minute the page becomes responsive again. is this not the case for you?

**Comment by alnmy** [comment] 2024-08-02 17:36
> @alnmy I am able to repro but after waiting for about a minute the page becomes responsive again. is this not the case for you?

This is the case for me aswell however yesterday Chromium gave me the "Pages unresponsive" prompt. I'm not sure what has changed since then that I no longer get it.

**Comment by qoijjj** [comment] 2024-08-02 17:36
useMemo is a react hook that caches the result of expensive operations. I thought maybe the disk-cache-dir change we make was affecting this, but I overrode it with a custom disk cache dir and can still repro

**Comment by qoijjj** [comment] 2024-08-02 17:37
@alnmy I think that just pops up after a certain amount of time passes waiting for a function to complete. could be a bunch of other conditions making it take a bit longer sometimes

**Comment by qoijjj** [comment] 2024-08-02 17:37
like other apps running, cpu clock speed, etc

**Comment by qoijjj** [comment] 2024-08-02 17:47
the thing that doesn't make sense though is that we were already enabling these features via chromium.conf in secureblue before moving to hardened-chromium

**Comment by ldmitch** [comment] 2024-08-02 19:14
Can be reproduced on Safari on M1 Mac, with lockdown mode disabled. Takes ~20s after initial page load to render the full page before it becomes responsive
![image](https://github.com/user-attachments/assets/31730a05-e561-4438-8d0c-9de1022d54b5)

**Comment by qoijjj** [comment] 2024-08-02 19:40
@RKNF404 was able to repro on google chrome as well. looks like this is a Proton bug caused by a recent change on their end

@alnmy you can report it here https://proton.me/support/report-bug

**Closed by qoijjj** 2024-08-02 19:40 UTC
